### ISSUE TITLE
hi sorry for posting here.... dont know where else to go

### ISSUE THREAD

**Issue by shpookys** [SgtMook/Sahraki-Orbital-Works#4]
is this SgtMook the same SgtMook who worked on flash games back in the day
more specifically this?
https://www.kongregate.com/games/SgtMook/haven-prelude

**Comment by SgtMook** [comment]
Yes!

**Comment by shpookys** [comment]
nice! good to see your still kicking. what would u happen to be working on here?

**Comment by shpookys** [comment]
also would there happen to be a batter place than here to communicate?

**Comment by SgtMook** [comment]
This is in game scripting for Space Engineers. You can reach me on Discord at SgtMook#5573.
